spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SpringJpa
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    
